# Start a new snake game
http://localhost:3000/new?w=2&h=2

###
# Invalid method
POST http://localhost:3000/new?w=2&h=2

###
# Internal server error
http://localhost:3000/new?w=a&h=2

###
# Valid move set
POST http://localhost:3000/validate
Content-Type: application/json

{
    "state": {
        "gameId": "cd592766-62de-44be-a0fb-9ffb2dbaf785",
        "width": 2,
        "height": 2,
        "score": 0,
        "fruit": {
            "x": 0,
            "y": 1
        },
        "snake": {
            "x": 0,
            "y": 0,
            "velX": 1,
            "velY": 0
        }
    },
    "ticks": [
        {
            "velX": 1,
            "velY": 0
        },
        {
            "velX": 0,
            "velY": 1
        },
        {
            "velX": -1,
            "velY": 0
        }
    ]
}

###
# Invalid method
GET http://localhost:3000/validate

###
# Internal server error
POST http://localhost:3000/validate
Content-Type: application/json

{
    "state": {
        "width": "2"
    },
    "ticks": []
}

###
# Snake went out of bounds
POST http://localhost:3000/validate
Content-Type: application/json

{
    "state": {
        "gameId": "cd592766-62de-44be-a0fb-9ffb2dbaf785",
        "width": 2,
        "height": 2,
        "score": 0,
        "fruit": {
            "x": 0,
            "y": 1
        },
        "snake": {
            "x": 0,
            "y": 0,
            "velX": 1,
            "velY": 0
        }
    },
    "ticks": [
        {
            "velX": 1,
            "velY": 0
        },
        {
            "velX": 0,
            "velY": 1
        },
        {
            "velX": 0,
            "velY": 1
        }
    ]
}

###
# Snake went out of bounds (negative)
POST http://localhost:3000/validate
Content-Type: application/json

{
    "state": {
        "gameId": "cd592766-62de-44be-a0fb-9ffb2dbaf785",
        "width": 2,
        "height": 2,
        "score": 0,
        "fruit": {
            "x": 0,
            "y": 1
        },
        "snake": {
            "x": 0,
            "y": 0,
            "velX": 1,
            "velY": 0
        }
    },
    "ticks": [
        {
            "velX": 1,
            "velY": 0
        },
        {
            "velX": 0,
            "velY": 1
        },
        {
            "velX": -1,
            "velY": 0
        },
        {
            "velX": -1,
            "velY": 0
        }
    ]
}

###
# Snake stopped moving
POST http://localhost:3000/validate
Content-Type: application/json

{
    "state": {
        "gameId": "cd592766-62de-44be-a0fb-9ffb2dbaf785",
        "width": 2,
        "height": 2,
        "score": 0,
        "fruit": {
            "x": 0,
            "y": 1
        },
        "snake": {
            "x": 0,
            "y": 0,
            "velX": 1,
            "velY": 0
        }
    },
    "ticks": [
        {
            "velX": 1,
            "velY": 0
        },
        {
            "velX": 0,
            "velY": 1
        },
        {
            "velX": 0,
            "velY": 0
        }
    ]
}

###
# Snake moved diagonally
POST http://localhost:3000/validate
Content-Type: application/json

{
    "state": {
        "gameId": "cd592766-62de-44be-a0fb-9ffb2dbaf785",
        "width": 2,
        "height": 2,
        "score": 0,
        "fruit": {
            "x": 0,
            "y": 1
        },
        "snake": {
            "x": 0,
            "y": 0,
            "velX": 1,
            "velY": 0
        }
    },
    "ticks": [
        {
            "velX": 1,
            "velY": 0
        },
        {
            "velX": 0,
            "velY": 1
        },
        {
            "velX": -1,
            "velY": 1
        }
    ]
}

###
# Snake made 180-degree turn
POST http://localhost:3000/validate
Content-Type: application/json

{
    "state": {
        "gameId": "cd592766-62de-44be-a0fb-9ffb2dbaf785",
        "width": 2,
        "height": 2,
        "score": 0,
        "fruit": {
            "x": 0,
            "y": 1
        },
        "snake": {
            "x": 0,
            "y": 0,
            "velX": 1,
            "velY": 0
        }
    },
    "ticks": [
        {
            "velX": 1,
            "velY": 0
        },
        {
            "velX": 0,
            "velY": 1
        },
        {
            "velX": 0,
            "velY": -1
        }
    ]
}

###
# Fruit not found
POST http://localhost:3000/validate
Content-Type: application/json

{
    "state": {
        "gameId": "cd592766-62de-44be-a0fb-9ffb2dbaf785",
        "width": 2,
        "height": 2,
        "score": 0,
        "fruit": {
            "x": 0,
            "y": 1
        },
        "snake": {
            "x": 0,
            "y": 0,
            "velX": 1,
            "velY": 0
        }
    },
    "ticks": [
        {
            "velX": 1,
            "velY": 0
        },
        {
            "velX": 0,
            "velY": 1
        }
    ]
}
