###
# Valid move set
POST http://localhost:3000/api/validate-move-set
Content-Type: application/json

{
    "moves": [
        {
            "x": 1,
            "y": 1
        },
        {
            "x": 1,
            "y": 0
        },
        {
            "x": 0,
            "y": 0
        },
        {
            "x": 0,
            "y": 1
        }
    ],
    "score": 0,
    "size": 3
}

###
# Out of bound move set
POST http://localhost:3000/api/validate-move-set
Content-Type: application/json

{
    "moves": [
        {
            "x": 1,
            "y": 1
        },
        {
            "x": 1,
            "y": 2
        }
    ],
    "score": 0,
    "size": 2
}

###
# Out of bound move set (negative)
POST http://localhost:3000/api/validate-move-set
Content-Type: application/json

{
    "moves": [
        {
            "x": -1,
            "y": 1
        },
        {
            "x": 1,
            "y": 1
        }
    ],
    "score": 0,
    "size": 2
}

###
# Repeated move set
POST http://localhost:3000/api/validate-move-set
Content-Type: application/json

{
    "moves": [
        {
            "x": 1,
            "y": 1
        },
        {
            "x": 1,
            "y": 0
        },
        {
            "x": 1,
            "y": 0
        },
        {
            "x": 0,
            "y": 1
        }
    ],
    "score": 0,
    "size": 3
}

###
# Not adjacent move set
POST http://localhost:3000/api/validate-move-set
Content-Type: application/json

{
    "moves": [
        {
            "x": 1,
            "y": 1
        },
        {
            "x": 1,
            "y": 0
        },
        {
            "x": 0,
            "y": 1
        },
        {
            "x": 1,
            "y": 1
        }
    ],
    "score": 0,
    "size": 3
}

###
# Reversed move set
POST http://localhost:3000/api/validate-move-set
Content-Type: application/json

{
    "moves": [
        {
            "x": 1,
            "y": 1
        },
        {
            "x": 1,
            "y": 0
        },
        {
            "x": 0,
            "y": 0
        },
        {
            "x": 1,
            "y": 0
        }
    ],
    "score": 0,
    "size": 3
}
